
[staff_team]
urban_planning_department = 10000
higher_construction_department = 8000
lower_construction_department = 7000
police_plus = 6000
court = 5000
citizenship_office = 3000
police = 2000
orthodox_patriarch = 1000
copper_cleaning_manager = 500
utilities = 500
