name: SimpleJobs
version: '1.0-SNAPSHOT'
main: me.andrej123456789.simplejobs.SimpleJobs
api-version: '1.19'

libraries:
  - com.moandjiezana.toml:toml4j:0.7.2

commands:
  jobs:
    description: Main command for SimpleJobs plugin
    usage: '/jobs <action> [job] [difficulty]'
    permission: simplejobs.jobs
    permission-message: '&cYou do not have permission to use this command'

  staff_salary:
      description: Admin command for SimpleJobs plugin
      usage: '/staff_salary'
      permission: simplejobs.staff_salary
      permission-message: '&cYou do not have permission to use this command'
